import { DataTableColumn } from "@/components/data-table/types";
import { IOrder } from "./types";

export const OrderColumns: DataTableColumn<IOrder>[] = [
  {
    id: "id",
    header: "id",
    accessorKey: "id",
    initialWidth: 220,
    minWidth: 150,
    maxWidth: 300,
  },
  {
    id: "orderNumber",
    header: "orderNumber",
    accessorKey: "orderNumber",
    initialWidth: 150,
    minWidth: 100,
    maxWidth: 300,
  },
  {
    id: "customerName",
    header: "customerName",
    accessorKey: "id",
    initialWidth: 180,
    minWidth: 120,
    maxWidth: 300,
    render: (order) => order.customer.name,
  },
  {
    id: "customerEmail",
    header: "customerEmail",
    accessorKey: "id",
    initialWidth: 220,
    minWidth: 160,
    maxWidth: 300,
    render: (order) => order.customer.email,
  },
  {
    id: "address",
    header: "address",
    accessorKey: "id",
    initialWidth: 250,
    minWidth: 180,
    maxWidth: 300,
    render: (order) => order.shipping.address,
  },
  {
    id: "city",
    header: "city",
    accessorKey: "id",
    initialWidth: 150,
    minWidth: 100,
    render: (order) => order.shipping.city,
  },
  {
    id: "country",
    header: "country",
    accessorKey: "id",
    initialWidth: 160,
    minWidth: 100,
    maxWidth: 300,
    render: (order) => order.shipping.country,
  },
  {
    id: "postalCode",
    header: "postalCode",
    accessorKey: "id",
    initialWidth: 130,
    minWidth: 100,
    maxWidth: 300,
    render: (order) => order.shipping.postalCode,
  },
  {
    id: "paymentMethod",
    header: "paymentMethod",
    accessorKey: "id",
    initialWidth: 160,
    minWidth: 120,
    render: (order) => order.payment.method,
  },
  {
    id: "deliveryMethod",
    header: "deliveryMethod",
    accessorKey: "id",
    initialWidth: 160,
    minWidth: 120,
    maxWidth: 300,
    render: (order) => order.delivery.method,
  },
  {
    id: "price",
    header: "price",
    accessorKey: "id",
    initialWidth: 120,
    minWidth: 90,
    maxWidth: 300,
    render: (order) => order.totals.total,
  },
  {
    id: "isPaid",
    header: "isPaid",
    accessorKey: "id",
    initialWidth: 100,
    minWidth: 80,
    maxWidth: 300,
    render: (order) => String(order.payment.isPaid),
  },
  {
    id: "createdAt",
    header: "createdAt",
    accessorKey: "createdAt",
    initialWidth: 180,
    minWidth: 140,
    maxWidth: 300,
  },
  {
    id: "updatedAt",
    header: "updatedAt",
    accessorKey: "updatedAt",
    initialWidth: 180,
    minWidth: 140,
    maxWidth: 300,
  },
];

export const Orders: IOrder[] = [
  {
    id: "cms0ifi2r0006m4ualesgoszd",
    orderNumber: "ORD-1784992471870",
    createdAt: "2026-07-25 15:14:31.875",
    updatedAt: "2026-07-25 15:14:58.496",
    customer: { name: "janedoe", email: "janedoe@example.com" },
    shipping: {
      address: "714 Green St, Apt 2B",
      country: "United States",
      city: "New York",
      postalCode: "CA 94108",
    },
    items: [
      {
        id: "cms0ifi5c0007m4ua5fuim1hz",
        orderId: "cms0ifi2r0006m4ualesgoszd",
        productId: "cms0hvxjm006h3wuakimzot9p",
        variantId: "cms0hvybj006w3wuaz8vrp21a",
        title: "Under Armour Hoodie",
        sku: "HOOD-UA-WHT-50",
        price: 7790,
        quantity: 1,
        selectedColor: "White",
        selectedSize: "50",
        image: "/products/hoodies/under-armour-white/image-1-480.png",
      },
      {
        id: "cms0ifi5c0008m4ua8nmdviak",
        orderId: "cms0ifi2r0006m4ualesgoszd",
        productId: "cms0hw77900e33wuarj5bay17",
        variantId: "cms0hw8lz00fa3wuazscwlcip",
        title: "Adidas Sports Sneakers",
        sku: "SNRK-ADST-BLE-41",
        price: 7790,
        quantity: 1,
        selectedColor: "Blue",
        selectedSize: "41",
        image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
      },
    ],
    currency: "USD",
    totals: { items: 15580, discount: 0, delivery: 0, total: 15580 },
    status: "CANCELLED",
    payment: { method: "CARD", isPaid: false },
    delivery: { method: "PICKUP" },
  },
];
