import { DataTableColumn } from "@/components/data-table/types";
import { IOrder, IOrderItem } from "../types";
import PaymentMethod from "../components/payment-method";
import DeliveryMethod from "../components/delivery-method";
import PaymentStatus from "../components/payment-status";
import CellImage from "@/components/data-table/cell-image";
import SelectSize from "@/features/products/components/select-size";

export const ORDER_COLUMNS: DataTableColumn<IOrder>[] = [
  {
    id: "id",
    header: "id",
    accessorKey: "id",
    initialWidth: 220,
    minWidth: 150,
    maxWidth: 300,
  },
  {
    id: "orderNumber",
    header: "orderNumber",
    accessorKey: "orderNumber",
    initialWidth: 150,
    minWidth: 100,
    maxWidth: 300,
  },
  {
    id: "customerName",
    header: "customerName",
    accessor: (order) => order.customer.name,
    initialWidth: 180,
    minWidth: 120,
    maxWidth: 300,
    render: (order) => order.customer.name,
    editable: true,
  },
  {
    id: "customerEmail",
    header: "customerEmail",
    accessor: (order) => order.customer.email,
    initialWidth: 220,
    minWidth: 160,
    maxWidth: 300,
    render: (order) => order.customer.email,
    editable: true,
  },
  {
    id: "address",
    header: "address",
    accessor: (order) => order.shipping.address,
    initialWidth: 250,
    minWidth: 180,
    maxWidth: 300,
    render: (order) => order.shipping.address,
    editable: true,
  },
  {
    id: "city",
    header: "city",
    accessor: (order) => order.shipping.city,
    initialWidth: 150,
    minWidth: 100,
    maxWidth: 300,
    render: (order) => order.shipping.city,
    editable: true,
  },
  {
    id: "country",
    header: "country",
    accessor: (order) => order.shipping.country,
    initialWidth: 160,
    minWidth: 100,
    maxWidth: 300,
    render: (order) => order.shipping.country,
    editable: true,
  },
  {
    id: "postalCode",
    header: "postalCode",
    accessor: (order) => order.shipping.postalCode,
    initialWidth: 130,
    minWidth: 100,
    maxWidth: 300,
    render: (order) => order.shipping.postalCode,
    editable: true,
  },
  {
    id: "paymentMethod",
    header: "paymentMethod",
    accessor: (order) => order.payment.method,
    initialWidth: 160,
    minWidth: 120,
    maxWidth: 300,
    render: (order) => <PaymentMethod method={order.payment.method} />,
    filter: {
      type: "checkbox",
      options: [
        { label: "Card", value: "CARD" },
        { label: "Cash", value: "CASH" },
        { label: "PayPal", value: "PAYPAl" },
      ],
    },
    className: "px-0",
  },
  {
    id: "deliveryMethod",
    header: "deliveryMethod",
    accessor: (order) => order.delivery.method,
    initialWidth: 160,
    minWidth: 120,
    maxWidth: 300,
    render: (order) => <DeliveryMethod method={order.delivery.method} />,
    filter: {
      type: "checkbox",
      options: [
        { label: "Courier", value: "COURIER" },
        { label: "Pick up", value: "PICKUP" },
        { label: "Post", value: "POST" },
      ],
    },
    className: "px-0",
  },
  {
    id: "price",
    header: "price",
    accessor: (order) => order.totals.total,
    initialWidth: 120,
    minWidth: 90,
    maxWidth: 300,
    render: (order) => order.totals.total,
  },
  {
    id: "isPaid",
    header: "isPaid",
    accessor: (order) => order.payment.isPaid,
    initialWidth: 120,
    minWidth: 120,
    maxWidth: 300,
    render: (order) => <PaymentStatus isPaid={order.payment.isPaid} />,
    filter: {
      type: "checkbox",
      options: [
        { label: "Оплачен", value: "PAID" },
        { label: "Не оплачен", value: "" },
      ],
    },
    className: "px-0",
  },
  {
    id: "createdAt",
    header: "createdAt",
    accessorKey: "createdAt",
    initialWidth: 180,
    minWidth: 140,
    maxWidth: 300,
  },
  {
    id: "updatedAt",
    header: "updatedAt",
    accessorKey: "updatedAt",
    initialWidth: 180,
    minWidth: 140,
    maxWidth: 300,
  },
];

export const ORDERS_DATA: IOrder[] = [
  {
    id: "cms0ifi2r0006m4ualesgoszd1",
    orderNumber: "ORD-1784992471870",
    createdAt: "2026-07-25 15:14:31.875",
    updatedAt: "2026-07-25 15:14:58.496",
    customer: { name: "janedoe", email: "janedoe@example.com" },
    shipping: {
      address: "714 Green St, Apt 2B",
      country: "United States",
      city: "New York",
      postalCode: "CA 94108",
    },
    items: [
      {
        id: "cms0ifi5c0007m4ua5fuim1hz",
        orderId: "cms0ifi2r0006m4ualesgoszd",
        productId: "cms0hvxjm006h3wuakimzot9p",
        variantId: "cms0hvybj006w3wuaz8vrp21a",
        title: "Under Armour Hoodie",
        sku: "HOOD-UA-WHT-50",
        price: 7790,
        quantity: 1,
        selectedColor: "White",
        selectedSize: "50",
        image: "/products/hoodies/under-armour-white/image-1-480.png",
      },
      {
        id: "cms0ifi5c0008m4ua8nmdviak",
        orderId: "cms0ifi2r0006m4ualesgoszd",
        productId: "cms0hw77900e33wuarj5bay17",
        variantId: "cms0hw8lz00fa3wuazscwlcip",
        title: "Adidas Sports Sneakers",
        sku: "SNRK-ADST-BLE-41",
        price: 7790,
        quantity: 1,
        selectedColor: "Blue",
        selectedSize: "41",
        image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
      },
    ],
    currency: "USD",
    totals: { items: 15580, discount: 0, delivery: 0, total: 15580 },
    status: "CANCELLED",
    payment: { method: "CARD", isPaid: false },
    delivery: { method: "PICKUP" },
  },
  {
    id: "cms0ifi2r0006m4ualesgoszd2",
    orderNumber: "ORD-1784992471870",
    createdAt: "2026-07-25 15:14:31.875",
    updatedAt: "2026-07-25 15:14:58.496",
    customer: { name: "janedoe", email: "janedoe@example.com" },
    shipping: {
      address: "714 Green St, Apt 2B",
      country: "United States",
      city: "New York",
      postalCode: "CA 94108",
    },
    items: [
      {
        id: "cms0ifi5c0007m4ua5fuim1hz",
        orderId: "cms0ifi2r0006m4ualesgoszd",
        productId: "cms0hvxjm006h3wuakimzot9p",
        variantId: "cms0hvybj006w3wuaz8vrp21a",
        title: "Under Armour Hoodie",
        sku: "HOOD-UA-WHT-50",
        price: 7790,
        quantity: 1,
        selectedColor: "White",
        selectedSize: "50",
        image: "/products/hoodies/under-armour-white/image-1-480.png",
      },
      {
        id: "cms0ifi5c0008m4ua8nmdviak",
        orderId: "cms0ifi2r0006m4ualesgoszd",
        productId: "cms0hw77900e33wuarj5bay17",
        variantId: "cms0hw8lz00fa3wuazscwlcip",
        title: "Adidas Sports Sneakers",
        sku: "SNRK-ADST-BLE-41",
        price: 7790,
        quantity: 1,
        selectedColor: "Blue",
        selectedSize: "41",
        image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
      },
    ],
    currency: "USD",
    totals: { items: 15580, discount: 0, delivery: 0, total: 15580 },
    status: "CANCELLED",
    payment: { method: "CARD", isPaid: false },
    delivery: { method: "PICKUP" },
  },
  {
    id: "cms0ifi2r0006m4ualesgoszd3",
    orderNumber: "ORD-1784992471870",
    createdAt: "2026-07-25 15:14:31.875",
    updatedAt: "2026-07-25 15:14:58.496",
    customer: { name: "janedoe", email: "janedoe@example.com" },
    shipping: {
      address: "714 Green St, Apt 2B",
      country: "United States",
      city: "New York",
      postalCode: "CA 94108",
    },
    items: [
      {
        id: "cms0ifi5c0007m4ua5fuim1hz",
        orderId: "cms0ifi2r0006m4ualesgoszd",
        productId: "cms0hvxjm006h3wuakimzot9p",
        variantId: "cms0hvybj006w3wuaz8vrp21a",
        title: "Under Armour Hoodie",
        sku: "HOOD-UA-WHT-50",
        price: 7790,
        quantity: 1,
        selectedColor: "White",
        selectedSize: "50",
        image: "/products/hoodies/under-armour-white/image-1-480.png",
      },
      {
        id: "cms0ifi5c0008m4ua8nmdviak",
        orderId: "cms0ifi2r0006m4ualesgoszd",
        productId: "cms0hw77900e33wuarj5bay17",
        variantId: "cms0hw8lz00fa3wuazscwlcip",
        title: "Adidas Sports Sneakers",
        sku: "SNRK-ADST-BLE-41",
        price: 7790,
        quantity: 1,
        selectedColor: "Blue",
        selectedSize: "41",
        image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
      },
    ],
    currency: "USD",
    totals: { items: 15580, discount: 0, delivery: 0, total: 15580 },
    status: "CANCELLED",
    payment: { method: "CARD", isPaid: false },
    delivery: { method: "PICKUP" },
  },
  {
    id: "cms0ifi2r0006m4ualesgoszd4",
    orderNumber: "ORD-1784992471870",
    createdAt: "2026-07-25 15:14:31.875",
    updatedAt: "2026-07-25 15:14:58.496",
    customer: { name: "janedoe", email: "janedoe@example.com" },
    shipping: {
      address: "714 Green St, Apt 2B",
      country: "United States",
      city: "New York",
      postalCode: "CA 94108",
    },
    items: [
      {
        id: "cms0ifi5c0007m4ua5fuim1hz",
        orderId: "cms0ifi2r0006m4ualesgoszd",
        productId: "cms0hvxjm006h3wuakimzot9p",
        variantId: "cms0hvybj006w3wuaz8vrp21a",
        title: "Under Armour Hoodie",
        sku: "HOOD-UA-WHT-50",
        price: 7790,
        quantity: 1,
        selectedColor: "White",
        selectedSize: "50",
        image: "/products/hoodies/under-armour-white/image-1-480.png",
      },
      {
        id: "cms0ifi5c0008m4ua8nmdviak",
        orderId: "cms0ifi2r0006m4ualesgoszd",
        productId: "cms0hw77900e33wuarj5bay17",
        variantId: "cms0hw8lz00fa3wuazscwlcip",
        title: "Adidas Sports Sneakers",
        sku: "SNRK-ADST-BLE-41",
        price: 7790,
        quantity: 1,
        selectedColor: "Blue",
        selectedSize: "41",
        image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
      },
    ],
    currency: "USD",
    totals: { items: 15580, discount: 0, delivery: 0, total: 15580 },
    status: "CANCELLED",
    payment: { method: "CARD", isPaid: false },
    delivery: { method: "PICKUP" },
  },
  {
    id: "cms0ifi2r0006m4ualesgoszd5",
    orderNumber: "ORD-1784992471870",
    createdAt: "2026-07-25 15:14:31.875",
    updatedAt: "2026-07-25 15:14:58.496",
    customer: { name: "janedoe", email: "janedoe@example.com" },
    shipping: {
      address: "714 Green St, Apt 2B",
      country: "United States",
      city: "New York",
      postalCode: "CA 94108",
    },
    items: [
      {
        id: "cms0ifi5c0007m4ua5fuim1hz",
        orderId: "cms0ifi2r0006m4ualesgoszd",
        productId: "cms0hvxjm006h3wuakimzot9p",
        variantId: "cms0hvybj006w3wuaz8vrp21a",
        title: "Under Armour Hoodie",
        sku: "HOOD-UA-WHT-50",
        price: 7790,
        quantity: 1,
        selectedColor: "White",
        selectedSize: "50",
        image: "/products/hoodies/under-armour-white/image-1-480.png",
      },
      {
        id: "cms0ifi5c0008m4ua8nmdviak",
        orderId: "cms0ifi2r0006m4ualesgoszd",
        productId: "cms0hw77900e33wuarj5bay17",
        variantId: "cms0hw8lz00fa3wuazscwlcip",
        title: "Adidas Sports Sneakers",
        sku: "SNRK-ADST-BLE-41",
        price: 7790,
        quantity: 1,
        selectedColor: "Blue",
        selectedSize: "41",
        image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
      },
    ],
    currency: "USD",
    totals: { items: 15580, discount: 0, delivery: 0, total: 15580 },
    status: "CANCELLED",
    payment: { method: "CARD", isPaid: false },
    delivery: { method: "PICKUP" },
  },
  {
    id: "cms0ifi2r0006m4ualesgoszd6",
    orderNumber: "ORD-1784992471870",
    createdAt: "2026-07-25 15:14:31.875",
    updatedAt: "2026-07-25 15:14:58.496",
    customer: { name: "alice", email: "janedoe@example.com" },
    shipping: {
      address: "714 Green St, Apt 2B",
      country: "United States",
      city: "New York",
      postalCode: "CA 94108",
    },
    items: [
      {
        id: "cms0ifi5c0007m4ua5fuim1hz",
        orderId: "cms0ifi2r0006m4ualesgoszd",
        productId: "cms0hvxjm006h3wuakimzot9p",
        variantId: "cms0hvybj006w3wuaz8vrp21a",
        title: "Under Armour Hoodie",
        sku: "HOOD-UA-WHT-50",
        price: 7790,
        quantity: 1,
        selectedColor: "White",
        selectedSize: "50",
        image: "/products/hoodies/under-armour-white/image-1-480.png",
      },
      {
        id: "cms0ifi5c0008m4ua8nmdviak",
        orderId: "cms0ifi2r0006m4ualesgoszd",
        productId: "cms0hw77900e33wuarj5bay17",
        variantId: "cms0hw8lz00fa3wuazscwlcip",
        title: "Adidas Sports Sneakers",
        sku: "SNRK-ADST-BLE-41",
        price: 7790,
        quantity: 1,
        selectedColor: "Blue",
        selectedSize: "41",
        image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
      },
    ],
    currency: "USD",
    totals: { items: 15580, discount: 0, delivery: 0, total: 15580 },
    status: "CANCELLED",
    payment: { method: "CARD", isPaid: false },
    delivery: { method: "PICKUP" },
  },
];

export const ORDER_ITEM_COLUMNS: DataTableColumn<IOrderItem>[] = [
  {
    id: "image",
    header: "image",
    accessorKey: "image",
    initialWidth: 100,
    minWidth: 100,
    maxWidth: 100,
    render: (item) => <CellImage src={item.image} alt={item.title} />,
  },
  {
    id: "productId",
    header: "productId",
    accessorKey: "productId",
    initialWidth: 220,
    minWidth: 150,
    maxWidth: 300,
  },
  {
    id: "variantId",
    header: "variantId",
    accessorKey: "variantId",
    initialWidth: 220,
    minWidth: 150,
    maxWidth: 300,
  },
  {
    id: "sku",
    header: "sku",
    accessorKey: "sku",
    initialWidth: 160,
    minWidth: 120,
    maxWidth: 300,
  },
  {
    id: "title",
    header: "title",
    accessorKey: "title",
    initialWidth: 220,
    minWidth: 150,
    maxWidth: 300,
  },
  {
    id: "selectedColor",
    header: "selectedColor",
    accessorKey: "selectedColor",
    initialWidth: 160,
    minWidth: 140,
    maxWidth: 300,
    editable: true,
  },
  {
    id: "selectedSize",
    header: "selectedSize",
    accessorKey: "selectedSize",
    initialWidth: 160,
    minWidth: 140,
    maxWidth: 300,
    render: (item) => (
      <SelectSize
        defaultSize={{ label: item.selectedSize, value: item.selectedSize }}
      />
    ),
  },
  {
    id: "price",
    header: "price",
    accessorKey: "price",
    initialWidth: 100,
    minWidth: 80,
    maxWidth: 300,
  },
  {
    id: "quantity",
    header: "quantity",
    accessorKey: "quantity",
    initialWidth: 120,
    minWidth: 80,
    maxWidth: 300,
    editable: true,
  },
];

export const ORDER_ITEMS: IOrderItem[] = [
  {
    id: "cms0ifi5c0007m4ua5fuim1hz1",
    orderId: "cms0ifi2r0006m4ualesgoszd",
    productId: "cms0hvxjm006h3wuakimzot9p",
    variantId: "cms0hvybj006w3wuaz8vrp21a",
    title: "Under Armour Hoodie",
    sku: "HOOD-UA-WHT-50",
    price: 7790,
    quantity: 1,
    selectedColor: "White",
    selectedSize: "50",
    image: "/products/hoodies/under-armour-white/image-1-480.png",
  },
  {
    id: "cms0ifi5c0008m4ua8nmdviak2",
    orderId: "cms0ifi2r0006m4ualesgoszd",
    productId: "cms0hw77900e33wuarj5bay17",
    variantId: "cms0hw8lz00fa3wuazscwlcip",
    title: "Adidas Sports Sneakers",
    sku: "SNRK-ADST-BLE-41",
    price: 7790,
    quantity: 1,
    selectedColor: "Blue",
    selectedSize: "41",
    image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
  },
  {
    id: "cms0ifi5c0008m4ua8nmdviak3",
    orderId: "cms0ifi2r0006m4ualesgoszd",
    productId: "cms0hw77900e33wuarj5bay17",
    variantId: "cms0hw8lz00fa3wuazscwlcip",
    title: "Adidas Sports Sneakers",
    sku: "SNRK-ADST-BLE-41",
    price: 7790,
    quantity: 1,
    selectedColor: "Blue",
    selectedSize: "41",
    image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
  },
  {
    id: "cms0ifi5c0008m4ua8nmdviak4",
    orderId: "cms0ifi2r0006m4ualesgoszd",
    productId: "cms0hw77900e33wuarj5bay17",
    variantId: "cms0hw8lz00fa3wuazscwlcip",
    title: "Adidas Sports Sneakers",
    sku: "SNRK-ADST-BLE-41",
    price: 7790,
    quantity: 1,
    selectedColor: "Blue",
    selectedSize: "41",
    image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
  },
  {
    id: "cms0ifi5c0008m4ua8nmdviak5",
    orderId: "cms0ifi2r0006m4ualesgoszd",
    productId: "cms0hw77900e33wuarj5bay17",
    variantId: "cms0hw8lz00fa3wuazscwlcip",
    title: "Adidas Sports Sneakers",
    sku: "SNRK-ADST-BLE-41",
    price: 7790,
    quantity: 1,
    selectedColor: "Blue",
    selectedSize: "41",
    image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
  },
  {
    id: "cms0ifi5c0008m4ua8nmdviak6",
    orderId: "cms0ifi2r0006m4ualesgoszd",
    productId: "cms0hw77900e33wuarj5bay17",
    variantId: "cms0hw8lz00fa3wuazscwlcip",
    title: "Adidas Sports Sneakers",
    sku: "SNRK-ADST-BLE-41",
    price: 7790,
    quantity: 1,
    selectedColor: "Blue",
    selectedSize: "41",
    image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
  },
  {
    id: "cms0ifi5c0008m4ua8nmdviak7",
    orderId: "cms0ifi2r0006m4ualesgoszd",
    productId: "cms0hw77900e33wuarj5bay17",
    variantId: "cms0hw8lz00fa3wuazscwlcip",
    title: "Adidas Sports Sneakers",
    sku: "SNRK-ADST-BLE-41",
    price: 7790,
    quantity: 1,
    selectedColor: "Blue",
    selectedSize: "41",
    image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
  },
  {
    id: "cms0ifi5c0008m4ua8nmdviak8",
    orderId: "cms0ifi2r0006m4ualesgoszd",
    productId: "cms0hw77900e33wuarj5bay17",
    variantId: "cms0hw8lz00fa3wuazscwlcip",
    title: "Adidas Sports Sneakers",
    sku: "SNRK-ADST-BLE-41",
    price: 7790,
    quantity: 1,
    selectedColor: "Blue",
    selectedSize: "41",
    image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
  },
  {
    id: "cms0ifi5c0008m4ua8nmdviak9",
    orderId: "cms0ifi2r0006m4ualesgoszd",
    productId: "cms0hw77900e33wuarj5bay17",
    variantId: "cms0hw8lz00fa3wuazscwlcip",
    title: "Adidas Sports Sneakers",
    sku: "SNRK-ADST-BLE-41",
    price: 7790,
    quantity: 1,
    selectedColor: "Blue",
    selectedSize: "41",
    image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
  },
  {
    id: "cms0ifi5c0008m4ua8nmdviak10",
    orderId: "cms0ifi2r0006m4ualesgoszd",
    productId: "cms0hw77900e33wuarj5bay17",
    variantId: "cms0hw8lz00fa3wuazscwlcip",
    title: "Adidas Sports Sneakers",
    sku: "SNRK-ADST-BLE-41",
    price: 7790,
    quantity: 1,
    selectedColor: "Blue",
    selectedSize: "41",
    image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
  },
  {
    id: "cms0ifi5c0008m4ua8nmdviak11",
    orderId: "cms0ifi2r0006m4ualesgoszd",
    productId: "cms0hw77900e33wuarj5bay17",
    variantId: "cms0hw8lz00fa3wuazscwlcip",
    title: "Adidas Sports Sneakers",
    sku: "SNRK-ADST-BLE-41",
    price: 7790,
    quantity: 1,
    selectedColor: "Blue",
    selectedSize: "41",
    image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
  },
  {
    id: "cms0ifi5c0008m4ua8nmdviak12",
    orderId: "cms0ifi2r0006m4ualesgoszd",
    productId: "cms0hw77900e33wuarj5bay17",
    variantId: "cms0hw8lz00fa3wuazscwlcip",
    title: "Adidas Sports Sneakers",
    sku: "SNRK-ADST-BLE-41",
    price: 7790,
    quantity: 1,
    selectedColor: "Blue",
    selectedSize: "41",
    image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
  },
  {
    id: "cms0ifi5c0008m4ua8nmdviak13",
    orderId: "cms0ifi2r0006m4ualesgoszd",
    productId: "cms0hw77900e33wuarj5bay17",
    variantId: "cms0hw8lz00fa3wuazscwlcip",
    title: "Adidas Sports Sneakers",
    sku: "SNRK-ADST-BLE-41",
    price: 7790,
    quantity: 1,
    selectedColor: "Blue",
    selectedSize: "41",
    image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
  },
  {
    id: "cms0ifi5c0008m4ua8nmdviak14",
    orderId: "cms0ifi2r0006m4ualesgoszd",
    productId: "cms0hw77900e33wuarj5bay17",
    variantId: "cms0hw8lz00fa3wuazscwlcip",
    title: "Adidas Sports Sneakers",
    sku: "SNRK-ADST-BLE-41",
    price: 7790,
    quantity: 1,
    selectedColor: "Blue",
    selectedSize: "41",
    image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
  },
  {
    id: "cms0ifi5c0008m4ua8nmdviak15",
    orderId: "cms0ifi2r0006m4ualesgoszd",
    productId: "cms0hw77900e33wuarj5bay17",
    variantId: "cms0hw8lz00fa3wuazscwlcip",
    title: "Adidas Sports Sneakers",
    sku: "SNRK-ADST-BLE-41",
    price: 7790,
    quantity: 1,
    selectedColor: "Blue",
    selectedSize: "41",
    image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
  },
  {
    id: "cms0ifi5c0008m4ua8nmdviak16",
    orderId: "cms0ifi2r0006m4ualesgoszd",
    productId: "cms0hw77900e33wuarj5bay17",
    variantId: "cms0hw8lz00fa3wuazscwlcip",
    title: "Adidas Sports Sneakers",
    sku: "SNRK-ADST-BLE-41",
    price: 7790,
    quantity: 1,
    selectedColor: "Blue",
    selectedSize: "41",
    image: "/products/sneakers/adidas-sports-blue/image-1-480.png",
  },
];
