import { DataTableColumn } from "@/components/data-table/types";
import { ICartItem, IFavorite, IUser } from "./types";
import CellImage from "@/components/data-table/cell-image";
import SelectSize from "../products/components/select-size";

export const CUSTOMER_COLUMNS: DataTableColumn<IUser>[] = [
  {
    id: "id",
    header: "id",
    accessorKey: "id",
    initialWidth: 220,
    minWidth: 150,
    maxWidth: 300,
  },
  {
    id: "name",
    header: "name",
    accessorKey: "name",
    initialWidth: 100,
    minWidth: 100,
    maxWidth: 300,
    editable: true,
    maxSymbols: 300,
  },
  {
    id: "email",
    header: "email",
    accessorKey: "email",
    initialWidth: 220,
    minWidth: 160,
    maxWidth: 300,
    editable: true,
    maxSymbols: 300,
  },
  {
    id: "recipient",
    header: "recipient",
    accessor: (user) => user.address.recipient,
    initialWidth: 100,
    minWidth: 100,
    maxWidth: 300,
    render: (user) => user.address.recipient,
    editable: true,
  },
  {
    id: "country",
    header: "country",
    accessor: (user) => user.address.country,
    initialWidth: 120,
    minWidth: 120,
    maxWidth: 300,
    render: (user) => user.address.country,
    editable: true,
  },
  {
    id: "city",
    header: "city",
    accessor: (user) => user.address.city,
    initialWidth: 120,
    minWidth: 120,
    maxWidth: 300,
    render: (user) => user.address.city,
    editable: true,
  },
  {
    id: "street",
    header: "street",
    accessor: (user) => user.address.street,
    initialWidth: 120,
    minWidth: 120,
    maxWidth: 300,
    render: (user) => user.address.street,
    editable: true,
  },
  {
    id: "postalCode",
    header: "postalCode",
    accessor: (user) => user.address.postalCode,
    initialWidth: 120,
    minWidth: 120,
    maxWidth: 300,
    render: (user) => user.address.postalCode,
    editable: true,
  },
  {
    id: "phone",
    header: "phone",
    accessor: (user) => user.address.phone,
    initialWidth: 120,
    minWidth: 120,
    maxWidth: 300,
    render: (user) => user.address.phone,
    editable: true,
  },
  {
    id: "createdAt",
    header: "createdAt",
    accessorKey: "createdAt",
    initialWidth: 150,
    minWidth: 100,
    maxWidth: 300,
  },
];

export const CUSTOMERS: IUser[] = [
  {
    id: "cms0hunvx001c2wua6bidro7m",
    name: "Jane Doe",
    email: "janedoe@example.com",
    createdAt: new Date(),
    address: {
      recipient: "null",
      country: "null",
      city: "null",
      street: "null",
      postalCode: "null",
      phone: "null",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  },
];

export const FAVORITE_COLUMNS: DataTableColumn<IFavorite>[] = [
  {
    id: "id",
    header: "id",
    accessorKey: "id",
    initialWidth: 220,
    minWidth: 150,
    maxWidth: 300,
  },
  {
    id: "productId",
    header: "productId",
    accessorKey: "productId",
    initialWidth: 220,
    minWidth: 150,
    maxWidth: 300,
  },
  {
    id: "createdAt",
    header: "createdAt",
    accessorKey: "createdAt",
    initialWidth: 220,
    minWidth: 150,
    maxWidth: 300,
  },
];

export const FAVORITES: IFavorite[] = [
  {
    id: "cms1vo4z5000c9kuavbgjzm3h",
    userId: "cms1tl1kv0009douag84wt28i",
    productId: "cms0hwc3o00i53wuar55ws1s8",
    createdAt: "2026-07-26 14:12:55.985",
  },
];

export const CART_COLUMNS: DataTableColumn<ICartItem>[] = [
  {
    id: "image",
    header: "image",
    accessorKey: "image",
    initialWidth: 100,
    minWidth: 100,
    maxWidth: 100,
    render: (item) => <CellImage alt={item.title} src={item.image} />,
  },
  {
    id: "id",
    header: "id",
    accessorKey: "id",
    initialWidth: 220,
    minWidth: 150,
    maxWidth: 300,
  },
  {
    id: "variantId",
    header: "variantId",
    accessorKey: "variantId",
    initialWidth: 220,
    minWidth: 160,
    maxWidth: 300,
  },
  {
    id: "sku",
    header: "sku",
    accessorKey: "sku",
    initialWidth: 150,
    minWidth: 150,
    maxWidth: 300,
  },
  {
    id: "slug",
    header: "slug",
    accessorKey: "slug",
    initialWidth: 220,
    minWidth: 150,
    maxWidth: 300,
  },
  {
    id: "brandName",
    header: "brandName",
    accessorKey: "brandName",
    initialWidth: 100,
    minWidth: 100,
    maxWidth: 300,
    editable: true,
  },
  {
    id: "categoryName",
    header: "categoryName",
    accessorKey: "categoryName",
    initialWidth: 120,
    minWidth: 120,
    maxWidth: 300,
    editable: true,
  },
  {
    id: "title",
    header: "title",
    accessorKey: "title",
    initialWidth: 220,
    minWidth: 150,
    maxWidth: 300,
    editable: true,
  },
  {
    id: "selectedColor",
    header: "selectedColor",
    accessor: (item) => item.selectedColor.value,
    initialWidth: 150,
    minWidth: 150,
    maxWidth: 300,
    editable: true,
  },
  {
    id: "selectedSize",
    header: "selectedSize",
    accessor: (item) => item.selectedSize,
    initialWidth: 150,
    minWidth: 150,
    maxWidth: 300,
    render: (item) => (
      <SelectSize
        defaultSize={{ label: item.selectedSize, value: item.selectedSize }}
      />
    ),
  },
  {
    id: "price",
    header: "price",
    accessorKey: "price",
    initialWidth: 100,
    minWidth: 100,
    maxWidth: 300,
    editable: true,
  },
  {
    id: "oldPrice",
    header: "oldPrice",
    accessorKey: "oldPrice",
    initialWidth: 100,
    minWidth: 100,
    maxWidth: 300,
    editable: true,
  },
  {
    id: "quantity",
    header: "quantity",
    accessorKey: "quantity",
    initialWidth: 100,
    minWidth: 100,
    maxWidth: 300,
    editable: true,
  },
  {
    id: "maxStock",
    header: "maxStock",
    accessorKey: "maxStock",
    initialWidth: 100,
    minWidth: 100,
    maxWidth: 300,
    editable: true,
  },
  {
    id: "createdAt",
    header: "createdAt",
    accessorKey: "createdAt",
    initialWidth: 220,
    minWidth: 150,
    maxWidth: 300,
  },
];

export const CART: ICartItem[] = [
  {
    id: "cms2vrt5p00011guavwgdok6m",
    cartItemId: "",
    title: "Adidas Originals FB T-Shirt",
    slug: "adidas-originals-fb-t-shirt",
    variantId: "cms0hwaqw00h33wua21vx6vk2",
    sku: "TSHT-ADFB-WHT-42",
    price: 7790,
    oldPrice: 9790,
    image: "/products/tshirts/adidas-originals-fb-white/image-1-480.png",
    selectedColor: { id: "cms0hwaf700gt3wuadfmkcz7a", value: "White" },
    selectedSize: "42",
    quantity: 1,
    maxStock: 5,
    brandName: "Adidas",
    categoryName: "T-Shirt",
    currency: "",
    createdAt: new Date(),
  },
];
